[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://dsa-flash-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
